spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3307/calculator?serverTimezone=UTC
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    #disable liquibase at start-up
    enabled: false


server:
  port: 8090